import { Terminal } from 'lucide-react'
import { IconType } from 'react-icons'
import {
  SiApache,
  SiApachecassandra,
  SiApachekafka,
  SiAngular,
  SiAstro,
  SiBun,
  SiCaddy,
  SiClickhouse,
  SiCockroachlabs,
  SiConsul,
  SiDeno,
  SiDocker,
  SiDotnet,
  SiElasticsearch,
  SiGo,
  SiGrafana,
  SiInfluxdb,
  SiKibana,
  SiKong,
  SiKubernetes,
  SiMinio,
  SiMongodb,
  SiMysql,
  SiNatsdotio,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNuxt,
  SiOpenjdk,
  SiPhp,
  SiPodman,
  SiPostgresql,
  SiPrometheus,
  SiPython,
  SiRabbitmq,
  SiRedis,
  SiRubyonrails,
  SiRust,
  SiSupabase,
  SiSvelte,
  SiTraefikproxy,
  SiVault,
  SiVite
} from 'react-icons/si'
import { TechKey, techKey } from 'src/shared/tech'

export { isKnownTech } from 'src/shared/tech'

// brand icon + color
const ICONS: Record<TechKey, [IconType, string?]> = {
  docker: [SiDocker, '#2496ED'],
  podman: [SiPodman, '#892CA0'],
  kubernetes: [SiKubernetes, '#326CE5'],
  next: [SiNextdotjs],
  nuxt: [SiNuxt, '#00DC82'],
  nest: [SiNestjs, '#E0234E'],
  vite: [SiVite, '#646CFF'],
  svelte: [SiSvelte, '#FF3E00'],
  astro: [SiAstro, '#BC52EE'],
  angular: [SiAngular, '#DD0031'],
  deno: [SiDeno],
  bun: [SiBun],
  node: [SiNodedotjs, '#5FA04E'],
  python: [SiPython, '#3776AB'],
  ruby: [SiRubyonrails, '#D30001'],
  php: [SiPhp, '#777BB4'],
  java: [SiOpenjdk, '#E76F00'],
  dotnet: [SiDotnet, '#512BD4'],
  go: [SiGo, '#00ADD8'],
  rust: [SiRust],
  postgres: [SiPostgresql, '#4169E1'],
  mysql: [SiMysql, '#4479A1'],
  cockroach: [SiCockroachlabs, '#6933FF'],
  redis: [SiRedis, '#FF4438'],
  mongo: [SiMongodb, '#47A248'],
  cassandra: [SiApachecassandra, '#1287B1'],
  clickhouse: [SiClickhouse, '#FFCC01'],
  influx: [SiInfluxdb, '#22ADF6'],
  minio: [SiMinio, '#C72E49'],
  supabase: [SiSupabase, '#3FCF8E'],
  elastic: [SiElasticsearch, '#FEC514'],
  kibana: [SiKibana, '#005571'],
  grafana: [SiGrafana, '#F46800'],
  prometheus: [SiPrometheus, '#E6522C'],
  rabbitmq: [SiRabbitmq, '#FF6600'],
  kafka: [SiApachekafka],
  nats: [SiNatsdotio, '#27AAE1'],
  nginx: [SiNginx, '#009639'],
  apache: [SiApache, '#D22128'],
  caddy: [SiCaddy, '#1F88C0'],
  traefik: [SiTraefikproxy, '#24A1C1'],
  kong: [SiKong, '#003459'],
  consul: [SiConsul, '#F24C53'],
  vault: [SiVault, '#FFEC6E']
}

export function iconFor(command: string): [IconType, string?] {
  const key = techKey(command)
  return key ? ICONS[key] : [Terminal, undefined]
}
